String message = "Hello, world!";
String message2 = message;
message += " My name is Tao!";
int[] values = {1, 2, 3, 4};
int[] values2 = values;
values[3] = 999;
double x = 7.2;
double x2 = x;
x += 12;